/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.StudentController;
import controller.TeacherController;

public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        qlSV = new javax.swing.JButton();
        qlGV = new javax.swing.JButton();
        qlMonHoc = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ThongKe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manager");
        setPreferredSize(new java.awt.Dimension(750, 420));
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 50));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quản lý", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Liberation Sans", 3, 18), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 100));
        jPanel1.setLayout(new java.awt.GridLayout(1, 3, 20, 0));

        qlSV.setText("Quản lý Sinh viên");
        qlSV.setPreferredSize(new java.awt.Dimension(800, 400));
        qlSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlSVActionPerformed(evt);
            }
        });
        jPanel1.add(qlSV);

        qlGV.setText("Quản lý Giảng viên");
        qlGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlGVActionPerformed(evt);
            }
        });
        jPanel1.add(qlGV);

        qlMonHoc.setText("Quản lý Môn học");
        qlMonHoc.setToolTipText("");
        jPanel1.add(qlMonHoc);

        getContentPane().add(jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(700, 100));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 50));

        ThongKe.setText("Thống kê");
        ThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThongKeActionPerformed(evt);
            }
        });
        jPanel2.add(ThongKe);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThongKeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ThongKeActionPerformed

    private void qlSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlSVActionPerformed
        StudentView studentView = new StudentView();
        StudentController studentController = new StudentController(studentView);
        studentController.showStudentView();      
    }//GEN-LAST:event_qlSVActionPerformed

    private void qlGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlGVActionPerformed
        TeacherView teacherView = new   TeacherView();
        TeacherController teacherController = new TeacherController(teacherView);
        teacherController.showTeacherView();
    }//GEN-LAST:event_qlGVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ThongKe;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton qlGV;
    private javax.swing.JButton qlMonHoc;
    private javax.swing.JButton qlSV;
    // End of variables declaration//GEN-END:variables
}
