/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.StudentController;
import controller.TeacherController;

public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTitle = new javax.swing.JPanel();
        txtNameCenter = new javax.swing.JLabel();
        pnGroupQuanLy = new javax.swing.JPanel();
        pnButton = new javax.swing.JPanel();
        qlSV = new javax.swing.JButton();
        qlGV = new javax.swing.JButton();
        qlMonHoc = new javax.swing.JButton();
        pnBtnThongKe = new javax.swing.JPanel();
        ThongKe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manager");
        setPreferredSize(new java.awt.Dimension(750, 420));
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 40));

        pnTitle.setForeground(new java.awt.Color(153, 153, 153));

        txtNameCenter.setFont(new java.awt.Font("Monospaced", 1, 28)); // NOI18N
        txtNameCenter.setForeground(new java.awt.Color(102, 102, 102));
        txtNameCenter.setText("Trung tâm ngoại ngữ TLinh");
        txtNameCenter.setToolTipText("");
        pnTitle.add(txtNameCenter);

        getContentPane().add(pnTitle);

        pnGroupQuanLy.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quản lý", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Liberation Sans", 3, 18), new java.awt.Color(0, 0, 255))); // NOI18N
        pnGroupQuanLy.setPreferredSize(new java.awt.Dimension(700, 100));

        pnButton.setLayout(new java.awt.GridLayout(1, 3, 40, 0));

        qlSV.setText("Quản lý Sinh viên");
        qlSV.setMaximumSize(new java.awt.Dimension(150, 50));
        qlSV.setPreferredSize(new java.awt.Dimension(150, 50));
        qlSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlSVActionPerformed(evt);
            }
        });
        pnButton.add(qlSV);

        qlGV.setText("Quản lý Giảng viên");
        qlGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlGVActionPerformed(evt);
            }
        });
        pnButton.add(qlGV);

        qlMonHoc.setText("Quản lý Khóa học");
        qlMonHoc.setToolTipText("");
        qlMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlMonHocActionPerformed(evt);
            }
        });
        pnButton.add(qlMonHoc);

        pnGroupQuanLy.add(pnButton);

        getContentPane().add(pnGroupQuanLy);

        pnBtnThongKe.setPreferredSize(new java.awt.Dimension(700, 100));
        pnBtnThongKe.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 50));

        ThongKe.setText("Thống kê");
        ThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThongKeActionPerformed(evt);
            }
        });
        pnBtnThongKe.add(ThongKe);

        getContentPane().add(pnBtnThongKe);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThongKeActionPerformed
        new ThongKeView().setVisible(true);
    }//GEN-LAST:event_ThongKeActionPerformed

    private void qlSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlSVActionPerformed
        StudentView studentView = new StudentView();
        StudentController studentController = new StudentController(studentView);
        studentController.showStudentView();      
    }//GEN-LAST:event_qlSVActionPerformed

    private void qlGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlGVActionPerformed
        TeacherView teacherView = new   TeacherView();
        TeacherController teacherController = new TeacherController(teacherView);
        teacherController.showTeacherView();
    }//GEN-LAST:event_qlGVActionPerformed

    private void qlMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlMonHocActionPerformed
        new KhoaHocView().setVisible(true);
    }//GEN-LAST:event_qlMonHocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ThongKe;
    private javax.swing.JPanel pnBtnThongKe;
    private javax.swing.JPanel pnButton;
    private javax.swing.JPanel pnGroupQuanLy;
    private javax.swing.JPanel pnTitle;
    private javax.swing.JButton qlGV;
    private javax.swing.JButton qlMonHoc;
    private javax.swing.JButton qlSV;
    private javax.swing.JLabel txtNameCenter;
    // End of variables declaration//GEN-END:variables
}
